# Generated by Django 5.0.6 on 2024-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='tempsmis',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='vrairep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
