# Generated by Django 5.0.6 on 2024-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userresponse_tempsmis_userresponse_vrairep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='tempsmis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
